# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64f9683a0efcd873ab900af59a85ddcd3cceb44c7512e955fc2f90ca81bcf534218b582daa5570050e59768e9a612c9ead0795b9c02b4d1bf0fda42ceea07fa

test:
  secret_key_base: 144803bfcb37897cbdf0d05a2ee6e3a7e78570fd324e6d0d4ef1e0bdd8e8d0eb7cf11f459205cfb057c88a092c9c4ca6c93597c6f21e8dac19b2332e683bc327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
